### ISSUE TITLE
HTTPS (#65) query forwarding

### ISSUE THREAD

**Issue by indexofrefraction** [rozahp/dnsmasq#3]
hi phazor,
i noticed that dnsmasq forwards [type=65] queries even if there is an address definition
eg **address=/doubleclick.net/127.0.0.1** is not working correctly, doubleclick.net gets forwarded
your patch to block HTTPS queries is a solution to suppress the dns leak
but even better would be to forward them as intended
best, index

**Comment by rozahp** [comment]
Sorry for very late reply .... Interesting idea, maybe one can do a recursive A-type lookup from the HTTPS-query and from that create a spoofed HTTPS-response to the client? I don't know if dnsmasq has logic to create a HTTPS-response?
